CREATE CACHED TABLE "USER_INFO"(
    "ID" INTEGER NOT NULL primary key,
    "ACCOUNT_ID" CHARACTER VARYING(100),
    "NAME" CHARACTER VARYING(50),
    "TOKEN" CHARACTER(36),
    "GMT_CREATE" BIGINT,
    "GMT_MODIFIED" BIGINT
)

